number1 = float(input("number1:"))
number2 = float(input("number2:"))
print("tổng:", number1+number2)
print("hiệu:", number1-number2)
print("tích:", number1*number2)
print("thương:", number1/number2)
print("chia nguyên:", number1//number2)
print("chia lấy dư:", number1 % number2)
print("lũy thừa:", number1**number2)
